export const products = [
  {
    name: "Jute Tote Bag",
    slug: "jute-tote-bag",
    img: "https://i.imgur.com/L0QiOHX.jpeg",
    description: ["Jute Tote Bag: JTB01", "Size: H 13 x W 15.5 inches"],
    images: [
      "https://i.imgur.com/L0QiOHX.jpeg",
      "https://i.imgur.com/d2GL9By.jpeg",
      "https://i.imgur.com/97EUYqM.jpeg",
      "https://i.imgur.com/GrJZGfo.jpeg",
      "https://i.imgur.com/UG3UeYj.jpeg",
      "https://i.imgur.com/VOM0hAK.jpeg",
      "https://i.imgur.com/9BMfs2S.jpeg",
      "https://i.imgur.com/MAdtk2W.jpeg",
      "https://i.imgur.com/KekHeXL.jpeg",
    ],
  },
  {
    name: "Jute Tote Bag",
    slug: "jute-tote-bag-02",
    img: "https://i.imgur.com/gMrAY2C.jpeg",
    description: ["Jute Tote Bag: JTB02", "Size: H 17.5 x W 17.5 inches"],
    images: [
      "https://i.imgur.com/gMrAY2C.jpeg",
      ".././p/2-2.jpg",
      ".././p/2-3.jpg",
      ".././p/2-4.jpg",
      ".././p/2-5.jpg",
      ".././p/2-6.jpg",
      ".././p/2-7.jpg",
    ],
  },
  {
    name: "Jute Hand Bag",
    slug: "jute-hand-bag",
    img: "https://i.imgur.com/YFE4WQN.jpeg",
    description: ["Jute Hand Bag: JHB03", "Size: H 10 x W 12 inches"],
    images: [
      "https://i.imgur.com/YFE4WQN.jpeg",
      ".././p/5-2.jpg",
      ".././p/5-3.jpg",
      ".././p/5-4.jpg",
      ".././p/5-5.jpg",
    ],
  },
  {
    name: "Jute Hand Bag",
    slug: "jute-hand-bag-04",
    img: "https://i.imgur.com/enZHMLg.jpeg",
    description: ["Jute Hand Bag: JHB04", "Size: H 9.5 x W 9 inches"],
    images: [
      "https://i.imgur.com/enZHMLg.jpeg",
      ".././p/4-2.jpg",
      ".././p/4-3.jpg",
      ".././p/4-4.jpg",
      ".././p/4-5.jpg",
    ],
  },
  {
    name: "Jute Sling Bag",
    slug: "jute-sling-bag",
    img: "https://i.imgur.com/SdIgubJ.jpeg",
    description: ["Jute Sling Bag: JSB05", "Size: H 10 x W 9 inches"],
    images: [
      "https://i.imgur.com/SdIgubJ.jpeg",
      ".././p/3-2.jpg",
      ".././p/3-3.jpg",
      ".././p/3-4.jpg",
      ".././p/3-5.jpg",
      ".././p/3-6.jpg",
      ".././p/3-7.jpg",
      ".././p/3-8.jpg",
    ],
  },
  {
    name: "Jute Sling Bag",
    slug: "jute-sling-bag-06",
    img: "https://i.imgur.com/IRtPSw4.jpeg",
    description: ["Jute Sling Bag: JSB06", "Size: H 6.5 x W 10 inches"],
    images: [
      "https://i.imgur.com/IRtPSw4.jpeg",
      ".././p/7-2.jpg",
      ".././p/7-3.jpg",
      ".././p/7-4.jpg",
    ],
  },
  {
    name: "Jute Sling Bag",
    slug: "jute-sling-bag-07",
    img: "https://i.imgur.com/T17pN6b.jpeg",
    description: ["Jute Sling Bag: JSB07", "Size: Diameter 7 inches"],
    images: [
      "https://i.imgur.com/T17pN6b.jpeg",
      ".././p/8-2.jpg",
      ".././p/8-3.jpg",
    ],
  },
  {
    name: "Jute Lunch Bag",
    slug: "jute-lunch-bag",
    img: "https://i.imgur.com/3pNjpVx.jpeg",
    description: ["Jute Lunch Bag: JLB08", "Size: H 7.5 x W 11 inches"],
    images: [
      "https://i.imgur.com/3pNjpVx.jpeg",
      ".././p/6-2.jpg",
      ".././p/6-3.jpg",
      ".././p/6-4.jpg",
    ],
  },
  {
    name: "Jute Pouch Bag",
    slug: "jute-pouch-bag",
    img: "https://i.imgur.com/daj3QpB.jpeg",
    description: ["Jute Pouch Bag: JSB05", "Size: H 4 x W 9 inches"],
    images: [
      "https://i.imgur.com/daj3QpB.jpeg",
      ".././p/9-1.jpg",
      ".././p/9-2.jpg",
      ".././p/9-3.jpg",
    ],
  },
];
